### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by tumido** [operate-first/installplan-operator#2]
and could we think about a more descriptive name for this repo? :)

_Originally posted by @goern in https://github.com/operate-first/update-approver/issues/1#issuecomment-803963239_

**Comment by tumido** [comment]
@goern @larsks 

what about `installplan-operator`?

**Comment by larsks** [comment]
That is a fine name for this bike shed. I'll make the change shortly.

**Comment by tumido** [comment]
@HumairAK wdyt?

**Comment by HumairAK** [comment]
I like `installplan-operator`

**Comment by tumido** [comment]
Repository renamed. Closing! :+1:
